#!/bin/sh

/etc/tests/ct-any-nut

ip -6 a a 3ffe:501:ffff:100:0200:ccff:fedd:eeff/64 dev eth0
ip -6 a a 3ffe:501:ffff:101:0201:ccff:fedd:eeff/64 dev eth1
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

