#!/bin/sh

echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/eth1/disable_ipv6

ip addr add 192.168.33.2/24 dev eth0
slattach -p slip -s 9600 /dev/ttyS1 &
sleep 1
ifconfig sl0 192.168.2.1 pointopoint 192.168.2.2 up

