LIB=	Cm
SRCS=	CmTypes.cc \
	BtObject.cc BtArray.cc BtList.cc BtSet.cc \
	CmQueue.cc CmAgent.cc CmMain.cc CmSocket.cc \
	CmFdSet.cc CmFdMasks.cc CmString.cc PerfCollect.cc \
	Timer.cc CmDispatch.cc CmReceiver.cc timeval.cc \
	CmToken.cc CmMatch.cc CmLexer.cc

CXXFLAGS+=	-I. 
CLEANFILES+=	.depend

.include "bsd.lib.mk"
